/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'p-primary': '#f7a501',
        'p-primary-pressed': '#dd9001',
        'p-primary-active': '#b17816',
        'p-on-primary': '#23251d',
        'p-ink': '#23251d',
        'p-body': '#4d4f46',
        'p-charcoal': '#33342d',
        'p-mute': '#6c6e63',
        'p-ash': '#9b9c92',
        'p-stone': '#b6b7af',
        'p-hair': '#bfc1b7',
        'p-hair-soft': '#dcdfd2',
        'p-canvas': '#eeefe9',
        'p-surface-soft': '#e5e7e0',
        'p-surface-card': '#ffffff',
        'p-surface-doc': '#fcfcfa',
        'p-surface-dark': '#23251d',
        'p-link': '#1d4ed8',
        'p-link-teal': '#1078a3',
        'p-accent-blue': '#2c84e0',
        'p-accent-blue-soft': '#dceaf6',
        'p-accent-red': '#cd4239',
        // Dark mode
        'p-dark-canvas': '#1a1a18',
        'p-dark-s1': '#23251d',
        'p-dark-s2': '#2a2c24',
        'p-dark-hair': '#3a3c34',
        'p-dark-hair-strong': '#4a4c44',
        'p-dark-ink': '#eeefe9',
        'p-dark-body': '#b6b7af',
        'p-dark-mute': '#9b9c92',
      },
      fontFamily: {
        'ph': ["'IBM Plex Sans'", "'Inter'", '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      borderRadius: {
        'p-xs': '4px',
        'p-sm': '6px',
        'p-md': '8px',
        'p-lg': '12px',
        'p-xl': '16px',
        'p-2xl': '20px',
        'p-full': '9999px',
      },
    },
  },
  plugins: [],
}
